## Use workflows from ninenines/ci.erlang.mk to test Ranch.

name: Check Ranch

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
      ## Every Monday at 4am.
      - cron: 0 4 * * 1

jobs:
  cleanup-master:
    name: Cleanup master build
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:

    - name: Cleanup master build if necessary
      if: ${{ github.event_name == 'schedule' }}
      run: |
        gh cache delete Linux-X64-Erlang-master -R $REPO || true
        gh cache delete macOS-ARM64-Erlang-master -R $REPO || true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}

  check:
    name: Ranch
    needs: cleanup-master
    uses: ninenines/ci.erlang.mk/.github/workflows/ci.yaml@master
